Vuex added, store is set up with example global vars
catenax-ng/product-battery-passport-consumer-app pull request #16
Opened 2022-08-12 07:34 UTC by davidzynda

## What this PR changes/adds

_Briefly describe WHAT your pr changes, which features it adds/modifies._

## Why it does that

_Briefly state why the change was necessary._

## Further notes

_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

## Linked Issue(s)

Closes # <-- _insert Issue number if one exists_

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [ ] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [ ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

2022-08-12 08:41 UTC, felixsteinke requested changes

2022-08-12 08:41 UTC, felixsteinke commented on src/components/Home.vue
> +  },
Your indentations are wrong. Please make sure to setup and use your editor configuration. 

For example i use IntelliJ and there is a "Reformat Code" option that manages these things automatically.

This is an issue in several lines.

2022-08-12 08:41 UTC, felixsteinke commented on src/components/Login.vue
> +
To keep the code clean, new lines should give more overview within the code. This new line is within an object definition and should be removed.

2022-08-12 08:41 UTC, felixsteinke commented on src/components/Login.vue
> +},
Like described in previous comments, please watch on your code style (indentions and unnecessary new lines).

2022-08-12 08:41 UTC, felixsteinke commented on src/components/BatteryPassport.vue
> +        v-bind:key="provider.id"
A lot of changes in the html are only related to changed __indentations__. You should really discuss a uniform editorconfig: https://editorconfig.org/ 

Most of the other comments also are related to that.

2022-08-12 08:41 UTC, felixsteinke commented on src/components/BatteryPassport.vue
> +
This is not a problem. But is really unnecessary in my opinion. 

Your editor should show you the local changes before the commit, in my opinion it is useful to look on all changes again, identify unnecessary changes like that and just remove/revert the change.

2022-08-12 08:41 UTC, felixsteinke commented on src/components/Header.vue
> +
same as in the other comments

2022-08-12 08:41 UTC, felixsteinke commented on src/store/index.js
> +import { createStore } from "vuex";
I did never use vuex, but the latest versions of VueJS use [Pinia](https://pinia.vuejs.org/) for state management. 
But as long as it does what you want it should be fine.

Just to let you know an alternative. ([Comparison of Pinia vs Vuex](https://blog.logrocket.com/pinia-vs-vuex/))

2022-08-12 08:43 UTC, felixsteinke commented
I had a lot of comments, mostly related to your IDE editor configuration. But especially the indentations are a sign of a dirty code. Because of that the review has requests for changes.

2022-08-18 12:54 UTC, felixsteinke commented
Just to let you know, you now merged the `dev branch` in here and this PR is for the `main`. I dont know if this is intended.

2022-08-18 13:10 UTC, felixsteinke commented on .github/workflows/publish-docker-images.yml
> +    branches: [ "main", "feature/CMP-16", "feature/CMP-150" ]
are this permanent branches? i thought they would only address single issues and therefore make sure you really want to put them into the action

2022-08-18 13:10 UTC, felixsteinke commented on src/components/BatteryPassport.vue
indentions are correct now, make sure to keep an eye on unnecessary new lines (whitespace)

2022-08-18 13:28 UTC, felixsteinke approved these changes
Looks good.

2022-08-18 14:49 UTC, saudkhan116 commented on .github/workflows/publish-docker-images.yml
> +    branches: [ "main", "feature/CMP-16", "feature/CMP-150" ]
these branches are just created temporarily in order to test the configuration in INT environment. They will be deleted once tests are done.

2022-08-18 14:56 UTC, saudkhan116 approved these changes
Looks fine to me. 
Please make sure to write a brief description in PR about what is implemented and what need to be done further related to the ticket.
Just a suggestion for future PR.

2022-08-19 07:10 UTC, closed without merging